name: Mobile + Release

on: workflow_dispatch

env:
  PROJECT_NAME: PsychEngine

jobs:

  build:
    strategy:
      matrix:
        include:

          - name: Android
            os: ubuntu-latest
            setupCommand: sh ./setup/unix.sh
            buildArgs: "android -final -D officialBuild"
            artifactName: androidBuild
            artifactPath: export/release/android/bin/app/build/outputs/apk/release/*.apk

          - name: iOS
            os: macos-14
            setupCommand: sh ./setup/unix.sh
            buildArgs: "ios -final -nosign -D officialBuild"
            artifactName: iosBuild
            artifactPath: export/release/ios/build/Release-iphoneos/*.ipa

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      setupCommand: ${{ matrix.setupCommand }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Android
        uses: actions/download-artifact@v4
        with:
          name: androidBuild
          path: build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: devbuild-${{ github.run_number }}
          name: DevBuild
          prerelease: true
          files: build/*.apk